import type {
  LiveStream,
  PodcastEpisode,
  PodcastChannel,
  PodcastCategory,
  Denomination,
  RoomParticipant,
} from '../types';

export const MOCK_LIVE_STREAMS: LiveStream[] = [
  {
    id: '1',
    title: 'Worship Night',
    hostId: 'host1',
    hostName: 'Grace Community',
    thumbnailEmoji: '🎵',
    viewerCount: 248,
    startedAt: new Date().toISOString(),
    streamUrl: '',
    isPublic: true,
    quality: '720p',
    denomination: null,
  },
  {
    id: '2',
    title: 'Sunday Service',
    hostId: 'host2',
    hostName: 'First Baptist',
    thumbnailEmoji: '⛪',
    viewerCount: 1500,
    startedAt: new Date().toISOString(),
    streamUrl: '',
    isPublic: true,
    quality: '1080p',
    denomination: 'Baptist',
  },
  {
    id: '3',
    title: 'Bible Study',
    hostId: 'host3',
    hostName: 'Word & Spirit',
    thumbnailEmoji: '📖',
    viewerCount: 532,
    startedAt: new Date().toISOString(),
    streamUrl: '',
    isPublic: true,
    quality: '720p',
    denomination: null,
  },
  {
    id: '4',
    title: 'Youth Meeting',
    hostId: 'host4',
    hostName: 'Youth Alive',
    thumbnailEmoji: '🙌',
    viewerCount: 89,
    startedAt: new Date().toISOString(),
    streamUrl: '',
    isPublic: true,
    quality: '720p',
    denomination: null,
  },
];

export const MOCK_PODCAST_EPISODES: PodcastEpisode[] = [
  {
    id: 'ep1',
    title: 'Understanding Grace in Daily Life',
    channelName: 'Faith & Hope Podcast',
    thumbnailEmoji: '🎙️',
    durationMinutes: 45,
    publishedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    audioUrl: '',
    isDownloaded: true,
    isSaved: false,
    playbackPosition: 0,
  },
  {
    id: 'ep2',
    title: "Psalms 23: The Shepherd's Care",
    channelName: 'Bible Deep Dive',
    thumbnailEmoji: '📖',
    durationMinutes: 32,
    publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    audioUrl: '',
    isDownloaded: false,
    isSaved: false,
    playbackPosition: 0,
  },
  {
    id: 'ep3',
    title: 'Starting Your Day with Purpose',
    channelName: 'Morning Prayer',
    thumbnailEmoji: '🙏',
    durationMinutes: 15,
    publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    audioUrl: '',
    isDownloaded: false,
    isSaved: false,
    playbackPosition: 0,
  },
  {
    id: 'ep4',
    title: 'Modern Faith Challenges',
    channelName: 'Theology Today',
    thumbnailEmoji: '✝️',
    durationMinutes: 58,
    publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    audioUrl: '',
    isDownloaded: false,
    isSaved: false,
    playbackPosition: 0,
  },
];

export const MOCK_PODCAST_CHANNELS: PodcastChannel[] = [
  { id: 'ch1', name: 'Faith & Hope Podcast', avatarEmoji: '🎙️', episodeCount: 152, subscriberCount: 24000, isSubscribed: false },
  { id: 'ch2', name: 'Bible Deep Dive', avatarEmoji: '📖', episodeCount: 98, subscriberCount: 18000, isSubscribed: false },
  { id: 'ch3', name: 'Morning Prayer', avatarEmoji: '🙏', episodeCount: 210, subscriberCount: 31000, isSubscribed: false },
  { id: 'ch4', name: 'Theology Today', avatarEmoji: '✝️', episodeCount: 76, subscriberCount: 15000, isSubscribed: false },
];

export const MOCK_PODCAST_CATEGORIES: PodcastCategory[] = [
  { id: 'cat1', name: 'Bible Study', icon: '📖', showCount: 45 },
  { id: 'cat2', name: 'Prayer', icon: '🙏', showCount: 32 },
  { id: 'cat3', name: 'Theology', icon: '✝️', showCount: 28 },
  { id: 'cat4', name: 'Worship', icon: '🎵', showCount: 38 },
  { id: 'cat5', name: 'Family', icon: '👨‍👩‍👧‍👦', showCount: 25 },
  { id: 'cat6', name: 'Leadership', icon: '💼', showCount: 19 },
  { id: 'cat7', name: 'Missions', icon: '🌍', showCount: 22 },
  { id: 'cat8', name: 'Teaching', icon: '📚', showCount: 41 },
];

export const MOCK_ROOM_PARTICIPANTS: RoomParticipant[] = [
  { id: 'p1', displayName: 'Pastor James', avatarEmoji: '👨‍💼', role: 'host', isMuted: false, isSpeaking: true },
  { id: 'p2', displayName: 'Sister Mary', avatarEmoji: '👩‍💼', role: 'speaker', isMuted: false, isSpeaking: false },
  { id: 'p3', displayName: 'Deacon Paul', avatarEmoji: '👴', role: 'speaker', isMuted: true, isSpeaking: false },
  { id: 'p4', displayName: 'Grace_M', avatarEmoji: '👩', role: 'listener', isMuted: true, isSpeaking: false },
  { id: 'p5', displayName: 'David_K', avatarEmoji: '👦', role: 'listener', isMuted: true, isSpeaking: false },
  { id: 'p6', displayName: 'Sarah_P', avatarEmoji: '👧', role: 'listener', isMuted: true, isSpeaking: false },
  { id: 'p7', displayName: 'Michael_R', avatarEmoji: '🧑', role: 'listener', isMuted: true, isSpeaking: false },
];

export const MOCK_DENOMINATIONS: Denomination[] = [
  {
    id: 'roman-catholic',
    name: 'Roman Catholic Church',
    group: 'CATHOLIC',
    description: 'The largest Christian church, led by the Pope in Rome. Known for its rich sacramental tradition, hierarchical structure, and continuity with the early church.',
    globalFollowers: '1.3 billion',
    bibleVersion: 'New American Bible',
    foundedYear: 33,
    worldwideMembers: '1,345,000,000',
  },
  {
    id: 'southern-baptist',
    name: 'Southern Baptist Convention',
    group: 'BAPTIST',
    description: 'The largest Protestant denomination in the United States, emphasizing believer\'s baptism, local church autonomy, and evangelism.',
    globalFollowers: '14 million',
    bibleVersion: 'KJV / ESV',
    foundedYear: 1845,
    worldwideMembers: '14,000,000',
  },
  {
    id: 'assemblies-of-god',
    name: 'Assemblies of God',
    group: 'PENTECOSTAL',
    description: 'One of the largest Pentecostal denominations worldwide, emphasizing the baptism of the Holy Spirit, speaking in tongues, and divine healing.',
    globalFollowers: '69 million',
    bibleVersion: 'NIV / ESV',
    foundedYear: 1914,
    worldwideMembers: '69,000,000',
  },
];
