/**
 * Hardcoded denomination catalogue (80 entries, 14 groups) from the curated CSV.
 * ponytail: frontend-only for now — migration 0008 seeds the same data server-side;
 * once applied, swap DenominationScreen back to useDenominations() and delete this.
 * Generated file — ids must stay stable (profiles.denomination_id references them).
 */
import type { Denomination } from '../types';

export const DENOMINATIONS: Denomination[] = [
  { id: 'roman-catholic', name: 'Roman Catholic Church', group: 'CATHOLIC', description: 'The largest Christian church, led by the Pope in Rome. Known for its rich sacramental tradition, hierarchical structure, and continuity with the early church.', globalFollowers: '1.3 billion', bibleVersion: 'New American Bible (NAB)', foundedYear: 33, worldwideMembers: '1,345,000,000' },
  { id: 'eastern-catholic-churches', name: 'Eastern Catholic Churches', group: 'CATHOLIC', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'old-catholic-church', name: 'Old Catholic Church', group: 'CATHOLIC', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'eastern-orthodox', name: 'Eastern Orthodox Church', group: 'ORTHODOX', description: 'One of the oldest branches of Christianity, emphasizing the seven ecumenical councils, theosis, and the divine liturgy. Known for its rich iconographic tradition.', globalFollowers: '260 million', bibleVersion: 'Orthodox Study Bible (OSB)', foundedYear: 33, worldwideMembers: '260,000,000' },
  { id: 'greek-orthodox-church', name: 'Greek Orthodox Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'russian-orthodox-church', name: 'Russian Orthodox Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'serbian-orthodox-church', name: 'Serbian Orthodox Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'romanian-orthodox-church', name: 'Romanian Orthodox Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'bulgarian-orthodox-church', name: 'Bulgarian Orthodox Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'coptic-orthodox-church', name: 'Coptic Orthodox Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'ethiopian-orthodox-church', name: 'Ethiopian Orthodox Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'armenian-apostolic-church', name: 'Armenian Apostolic Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'syriac-orthodox-church', name: 'Syriac Orthodox Church', group: 'ORTHODOX', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'anglican-episcopal-church', name: 'Anglican/Episcopal Church', group: 'PROTESTANT_MAINLINE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'lutheran', name: 'Lutheran Church', group: 'PROTESTANT_MAINLINE', description: 'Founded on the teachings of Martin Luther, Lutheranism emphasises justification by grace through faith alone, the authority of Scripture, and the two sacraments of baptism and communion.', globalFollowers: '77 million', bibleVersion: 'ESV / NIV', foundedYear: 1517, worldwideMembers: '77,000,000' },
  { id: 'methodist-church', name: 'Methodist Church', group: 'PROTESTANT_MAINLINE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'presbyterian-church', name: 'Presbyterian Church', group: 'PROTESTANT_MAINLINE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'reformed-church', name: 'Reformed Church', group: 'PROTESTANT_MAINLINE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'united-church-of-christ', name: 'United Church of Christ', group: 'PROTESTANT_MAINLINE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'congregational-church', name: 'Congregational Church', group: 'PROTESTANT_MAINLINE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'moravian-church', name: 'Moravian Church', group: 'PROTESTANT_MAINLINE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'baptist-churches', name: 'Baptist Churches', group: 'PROTESTANT_EVANGELICAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'southern-baptist', name: 'Southern Baptist Convention', group: 'PROTESTANT_EVANGELICAL', description: 'The largest Protestant denomination in the United States, emphasizing believer\'s baptism, local church autonomy, and a strong commitment to evangelism and missions.', globalFollowers: '14 million', bibleVersion: 'KJV / CSB', foundedYear: 1845, worldwideMembers: '14,000,000' },
  { id: 'american-baptist-churches', name: 'American Baptist Churches', group: 'PROTESTANT_EVANGELICAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'national-baptist-convention', name: 'National Baptist Convention', group: 'PROTESTANT_EVANGELICAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'evangelical-free-church', name: 'Evangelical Free Church', group: 'PROTESTANT_EVANGELICAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'bible-churches', name: 'Bible Churches', group: 'PROTESTANT_EVANGELICAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'missionary-church', name: 'Missionary Church', group: 'PROTESTANT_EVANGELICAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'evangelical-covenant-church', name: 'Evangelical Covenant Church', group: 'PROTESTANT_EVANGELICAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'assemblies-of-god', name: 'Assemblies of God', group: 'PENTECOSTAL', description: 'One of the largest Pentecostal denominations worldwide, emphasizing the baptism of the Holy Spirit, speaking in tongues, and divine healing.', globalFollowers: '69 million', bibleVersion: 'NIV / ESV', foundedYear: 1914, worldwideMembers: '69,000,000' },
  { id: 'church-of-god-cleveland', name: 'Church of God (Cleveland)', group: 'PENTECOSTAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'pentecostal-holiness-church', name: 'Pentecostal Holiness Church', group: 'PENTECOSTAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'international-church-of-the-foursquare-gospel', name: 'International Church of the Foursquare Gospel', group: 'PENTECOSTAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'church-of-god-in-christ-cogic', name: 'Church of God in Christ (COGIC)', group: 'PENTECOSTAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'apostolic-pentecostal-churches', name: 'Apostolic Pentecostal Churches', group: 'PENTECOSTAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'united-pentecostal-church', name: 'United Pentecostal Church', group: 'PENTECOSTAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'vineyard-churches', name: 'Vineyard Churches', group: 'CHARISMATIC', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'calvary-chapel', name: 'Calvary Chapel', group: 'CHARISMATIC', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'word-of-faith-movement', name: 'Word of Faith Movement', group: 'CHARISMATIC', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'bethel-church-movement', name: 'Bethel Church Movement', group: 'CHARISMATIC', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'hillsong-church', name: 'Hillsong Church', group: 'CHARISMATIC', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'african-methodist-episcopal-ame', name: 'African Methodist Episcopal (AME)', group: 'HISTORICALLY_BLACK', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'ame-zion-church', name: 'AME Zion Church', group: 'HISTORICALLY_BLACK', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'christian-methodist-episcopal', name: 'Christian Methodist Episcopal', group: 'HISTORICALLY_BLACK', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'progressive-national-baptist-convention', name: 'Progressive National Baptist Convention', group: 'HISTORICALLY_BLACK', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'mennonite-church', name: 'Mennonite Church', group: 'PEACE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'amish', name: 'Amish', group: 'PEACE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'quaker-society-of-friends', name: 'Quaker (Society of Friends)', group: 'PEACE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'church-of-the-brethren', name: 'Church of the Brethren', group: 'PEACE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'hutterite-brethren', name: 'Hutterite Brethren', group: 'PEACE', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'church-of-the-nazarene', name: 'Church of the Nazarene', group: 'HOLINESS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'wesleyan-church', name: 'Wesleyan Church', group: 'HOLINESS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'free-methodist-church', name: 'Free Methodist Church', group: 'HOLINESS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'salvation-army', name: 'Salvation Army', group: 'HOLINESS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'christian-and-missionary-alliance', name: 'Christian and Missionary Alliance', group: 'HOLINESS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'churches-of-christ', name: 'Churches of Christ', group: 'RESTORATIONIST', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'christian-church-disciples-of-christ', name: 'Christian Church (Disciples of Christ)', group: 'RESTORATIONIST', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'independent-christian-churches', name: 'Independent Christian Churches', group: 'RESTORATIONIST', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'latter-day-saints-mormon', name: 'Latter-day Saints (Mormon)', group: 'RESTORATIONIST', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'seventh-day-adventist', name: 'Seventh-day Adventist Church', group: 'RESTORATIONIST', description: 'A Protestant Christian denomination known for its emphasis on the Saturday Sabbath, holistic health, and the imminent second coming of Jesus Christ.', globalFollowers: '21 million', bibleVersion: 'NKJV / NIV', foundedYear: 1863, worldwideMembers: '21,000,000' },
  { id: 'jehovah-s-witnesses', name: 'Jehovah\'s Witnesses', group: 'RESTORATIONIST', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'christadelphians', name: 'Christadelphians', group: 'RESTORATIONIST', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'non-denominational-churches', name: 'Non-Denominational Churches', group: 'NON_DENOMINATIONAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'community-churches', name: 'Community Churches', group: 'NON_DENOMINATIONAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'independent-churches', name: 'Independent Churches', group: 'NON_DENOMINATIONAL', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'zion-christian-church', name: 'Zion Christian Church', group: 'AFRICAN_INDIGENOUS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'kimbanguist-church', name: 'Kimbanguist Church', group: 'AFRICAN_INDIGENOUS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'aladura-churches', name: 'Aladura Churches', group: 'AFRICAN_INDIGENOUS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'cherubim-and-seraphim', name: 'Cherubim and Seraphim', group: 'AFRICAN_INDIGENOUS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'african-initiated-churches', name: 'African Initiated Churches', group: 'AFRICAN_INDIGENOUS', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'chinese-house-churches', name: 'Chinese House Churches', group: 'ASIAN', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'true-jesus-church', name: 'True Jesus Church', group: 'ASIAN', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'local-church-movement', name: 'Local Church Movement', group: 'ASIAN', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'yoido-full-gospel-church', name: 'Yoido Full Gospel Church', group: 'ASIAN', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'unity-church', name: 'Unity Church', group: 'OTHER', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'science-of-mind', name: 'Science of Mind', group: 'OTHER', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'unitarian-universalist', name: 'Unitarian Universalist', group: 'OTHER', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'swedenborgian-church', name: 'Swedenborgian Church', group: 'OTHER', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'plymouth-brethren', name: 'Plymouth Brethren', group: 'OTHER', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
  { id: 'messianic-judaism', name: 'Messianic Judaism', group: 'OTHER', description: '', globalFollowers: '', bibleVersion: '', foundedYear: 0, worldwideMembers: '' },
];
