-- 0008_denominations_all.sql
-- Full denomination catalogue (81 entries, 14 groups) from the curated CSV.
-- Existing curated rows keep their descriptions/stats: the upsert only updates
-- name, group, and sort_order. New rows use the table's empty-string defaults.

set search_path = public;

-- Widen the group check to the new taxonomy (legacy BAPTIST/ADVENTIST kept so
-- the constraint is valid before the upsert re-groups those rows).
alter table public.denominations drop constraint if exists denominations_group_check;
alter table public.denominations add constraint denominations_group_check check ("group" in (
  'CATHOLIC', 'ORTHODOX', 'PROTESTANT_MAINLINE', 'PROTESTANT_EVANGELICAL',
  'PENTECOSTAL', 'CHARISMATIC', 'HISTORICALLY_BLACK', 'PEACE', 'HOLINESS',
  'RESTORATIONIST', 'NON_DENOMINATIONAL', 'AFRICAN_INDIGENOUS', 'ASIAN', 'OTHER',
  'BAPTIST', 'ADVENTIST'
));

insert into public.denominations (id, name, "group", sort_order) values
  ('roman-catholic', 'Roman Catholic Church', 'CATHOLIC', 10),
  ('eastern-catholic-churches', 'Eastern Catholic Churches', 'CATHOLIC', 20),
  ('old-catholic-church', 'Old Catholic Church', 'CATHOLIC', 30),
  ('eastern-orthodox', 'Eastern Orthodox Church', 'ORTHODOX', 40),
  ('greek-orthodox-church', 'Greek Orthodox Church', 'ORTHODOX', 50),
  ('russian-orthodox-church', 'Russian Orthodox Church', 'ORTHODOX', 60),
  ('serbian-orthodox-church', 'Serbian Orthodox Church', 'ORTHODOX', 70),
  ('romanian-orthodox-church', 'Romanian Orthodox Church', 'ORTHODOX', 80),
  ('bulgarian-orthodox-church', 'Bulgarian Orthodox Church', 'ORTHODOX', 90),
  ('coptic-orthodox-church', 'Coptic Orthodox Church', 'ORTHODOX', 100),
  ('ethiopian-orthodox-church', 'Ethiopian Orthodox Church', 'ORTHODOX', 110),
  ('armenian-apostolic-church', 'Armenian Apostolic Church', 'ORTHODOX', 120),
  ('syriac-orthodox-church', 'Syriac Orthodox Church', 'ORTHODOX', 130),
  ('anglican-episcopal-church', 'Anglican/Episcopal Church', 'PROTESTANT_MAINLINE', 140),
  ('lutheran', 'Lutheran Church', 'PROTESTANT_MAINLINE', 150),
  ('methodist-church', 'Methodist Church', 'PROTESTANT_MAINLINE', 160),
  ('presbyterian-church', 'Presbyterian Church', 'PROTESTANT_MAINLINE', 170),
  ('reformed-church', 'Reformed Church', 'PROTESTANT_MAINLINE', 180),
  ('united-church-of-christ', 'United Church of Christ', 'PROTESTANT_MAINLINE', 190),
  ('congregational-church', 'Congregational Church', 'PROTESTANT_MAINLINE', 200),
  ('moravian-church', 'Moravian Church', 'PROTESTANT_MAINLINE', 210),
  ('baptist-churches', 'Baptist Churches', 'PROTESTANT_EVANGELICAL', 220),
  ('southern-baptist', 'Southern Baptist Convention', 'PROTESTANT_EVANGELICAL', 230),
  ('american-baptist-churches', 'American Baptist Churches', 'PROTESTANT_EVANGELICAL', 240),
  ('national-baptist-convention', 'National Baptist Convention', 'PROTESTANT_EVANGELICAL', 250),
  ('evangelical-free-church', 'Evangelical Free Church', 'PROTESTANT_EVANGELICAL', 260),
  ('bible-churches', 'Bible Churches', 'PROTESTANT_EVANGELICAL', 270),
  ('missionary-church', 'Missionary Church', 'PROTESTANT_EVANGELICAL', 280),
  ('evangelical-covenant-church', 'Evangelical Covenant Church', 'PROTESTANT_EVANGELICAL', 290),
  ('assemblies-of-god', 'Assemblies of God', 'PENTECOSTAL', 300),
  ('church-of-god-cleveland', 'Church of God (Cleveland)', 'PENTECOSTAL', 310),
  ('pentecostal-holiness-church', 'Pentecostal Holiness Church', 'PENTECOSTAL', 320),
  ('international-church-of-the-foursquare-gospel', 'International Church of the Foursquare Gospel', 'PENTECOSTAL', 330),
  ('church-of-god-in-christ-cogic', 'Church of God in Christ (COGIC)', 'PENTECOSTAL', 340),
  ('apostolic-pentecostal-churches', 'Apostolic Pentecostal Churches', 'PENTECOSTAL', 350),
  ('united-pentecostal-church', 'United Pentecostal Church', 'PENTECOSTAL', 360),
  ('vineyard-churches', 'Vineyard Churches', 'CHARISMATIC', 370),
  ('calvary-chapel', 'Calvary Chapel', 'CHARISMATIC', 380),
  ('word-of-faith-movement', 'Word of Faith Movement', 'CHARISMATIC', 390),
  ('bethel-church-movement', 'Bethel Church Movement', 'CHARISMATIC', 400),
  ('hillsong-church', 'Hillsong Church', 'CHARISMATIC', 410),
  ('african-methodist-episcopal-ame', 'African Methodist Episcopal (AME)', 'HISTORICALLY_BLACK', 420),
  ('ame-zion-church', 'AME Zion Church', 'HISTORICALLY_BLACK', 430),
  ('christian-methodist-episcopal', 'Christian Methodist Episcopal', 'HISTORICALLY_BLACK', 440),
  ('progressive-national-baptist-convention', 'Progressive National Baptist Convention', 'HISTORICALLY_BLACK', 450),
  ('mennonite-church', 'Mennonite Church', 'PEACE', 460),
  ('amish', 'Amish', 'PEACE', 470),
  ('quaker-society-of-friends', 'Quaker (Society of Friends)', 'PEACE', 480),
  ('church-of-the-brethren', 'Church of the Brethren', 'PEACE', 490),
  ('hutterite-brethren', 'Hutterite Brethren', 'PEACE', 500),
  ('church-of-the-nazarene', 'Church of the Nazarene', 'HOLINESS', 510),
  ('wesleyan-church', 'Wesleyan Church', 'HOLINESS', 520),
  ('free-methodist-church', 'Free Methodist Church', 'HOLINESS', 530),
  ('salvation-army', 'Salvation Army', 'HOLINESS', 540),
  ('christian-and-missionary-alliance', 'Christian and Missionary Alliance', 'HOLINESS', 550),
  ('churches-of-christ', 'Churches of Christ', 'RESTORATIONIST', 560),
  ('christian-church-disciples-of-christ', 'Christian Church (Disciples of Christ)', 'RESTORATIONIST', 570),
  ('independent-christian-churches', 'Independent Christian Churches', 'RESTORATIONIST', 580),
  ('latter-day-saints-mormon', 'Latter-day Saints (Mormon)', 'RESTORATIONIST', 590),
  ('seventh-day-adventist', 'Seventh-day Adventist Church', 'RESTORATIONIST', 600),
  ('jehovah-s-witnesses', 'Jehovah''s Witnesses', 'RESTORATIONIST', 610),
  ('christadelphians', 'Christadelphians', 'RESTORATIONIST', 620),
  ('non-denominational-churches', 'Non-Denominational Churches', 'NON_DENOMINATIONAL', 630),
  ('community-churches', 'Community Churches', 'NON_DENOMINATIONAL', 640),
  ('independent-churches', 'Independent Churches', 'NON_DENOMINATIONAL', 650),
  ('zion-christian-church', 'Zion Christian Church', 'AFRICAN_INDIGENOUS', 660),
  ('kimbanguist-church', 'Kimbanguist Church', 'AFRICAN_INDIGENOUS', 670),
  ('aladura-churches', 'Aladura Churches', 'AFRICAN_INDIGENOUS', 680),
  ('cherubim-and-seraphim', 'Cherubim and Seraphim', 'AFRICAN_INDIGENOUS', 690),
  ('african-initiated-churches', 'African Initiated Churches', 'AFRICAN_INDIGENOUS', 700),
  ('chinese-house-churches', 'Chinese House Churches', 'ASIAN', 710),
  ('true-jesus-church', 'True Jesus Church', 'ASIAN', 720),
  ('local-church-movement', 'Local Church Movement', 'ASIAN', 730),
  ('yoido-full-gospel-church', 'Yoido Full Gospel Church', 'ASIAN', 740),
  ('unity-church', 'Unity Church', 'OTHER', 750),
  ('science-of-mind', 'Science of Mind', 'OTHER', 760),
  ('unitarian-universalist', 'Unitarian Universalist', 'OTHER', 770),
  ('swedenborgian-church', 'Swedenborgian Church', 'OTHER', 780),
  ('plymouth-brethren', 'Plymouth Brethren', 'OTHER', 790),
  ('messianic-judaism', 'Messianic Judaism', 'OTHER', 800)
on conflict (id) do update set
  name       = excluded.name,
  "group"    = excluded."group",
  sort_order = excluded.sort_order;
